# Generated by Django 3.1 on 2020-08-19 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_auto_20200818_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='lecture_course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.courses'),
        ),
    ]
